#!/usr/bin/env bash
#
#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2013-2015
#
# VERSION 5
#
# AVEC 1 paramètre : /path/to/archlinux.iso
# Example : $ iso2usb ~/99-Isos/archlinux-2012.12.01-dual.iso
# ou
# SANS PARAMETRE : par défaut dans /home/jnd/99-Isos
# Example : $ iso2usb
#

# COULEURS
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
BLUE="${BOLD}\e[1;34m"
GREEN="${BOLD}\e[1;32m"
RED="${BOLD}\e[1;31m"
YELLOW="${BOLD}\e[1;33m"

# FONCTIONS
msg_titre() {
        local mesg=$1; shift
        printf "${BOLD}${mesg}${ALL_OFF}\n" "$@" >&2
}

msg() {
        local mesg=$1; shift
        printf "${BOLD}:: ${mesg}${ALL_OFF}\n" "$@" >&2
}

msg_grenn() {
        local mesg=$1; shift
        printf "${GREEN}:: ${mesg}${ALL_OFF}\n" "$@" >&2
}

error() {
        local mesg=$1; shift
        printf "${RED}==> ERREUR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

cleanup() {
        [[ $1 ]] && exit $1
}

die() {
        error "$*"
        cleanup 1
}

read_key() {
    echo -e "${YELLOW}"
    read -p "$1 et appuyer sur une touche" OPTION
    echo -e "${ALL_OFF}"
}

contains_element() {
    #check if an element exist in a string
    for e in "${@:2}"; do [[ $e == $1 ]] && break; done;
}

invalid_option() {
    echo -e "${RED}Option invalide. Essayez une autre option.${ALL_OFF}"
}

# Variables globales
IS_USB_KEY=0
DEVICE_USB_KEY=""
PATH_TO_ISO=""
DIR_ISOS="/home/jnd/99-Isos"

# Variables du script
nom_script="$0"
nombre_d_argument="$#"
path_to_iso="$1"

# => Passe en root
if [ ! $( id -u ) -eq 0 ]; then
    echo -e "\n${YELLOW}Le script "$0" doit être exécuté en << root >>."
    echo -e "Entrer le mot de passe de << root >>${ALL_OFF}"
    exec su -c "${0} ${1}"
    exit ${?}
fi

# Titre
msg_titre "+------------------------------------------------+"
msg_titre "|                                                |"
msg_titre "|       Écriture de fichier ISO sur clé USB      |"
msg_titre "|                                                |"
msg_titre "+------------------------------------------------+"

# Test si 1 argument
if [[ $# -eq 1 ]]; then
    # Test si $1 = archlinux.iso existe et est un fichier
    if [[ ! -f "$1" ]]; then
        die "Le ficher ""$1" "n'existe pas. Usage : iso2usb /chemin/vers/archlinux.iso""\n"
    else
        PATH_TO_ISO="$1"
    fi
else
    # Pas d'argument. Fabrique une liste des isos
    liste_isos=($(LC_ALL=C ls "${DIR_ISOS}" | grep -E ".iso$"))
    PS3="Entrer le n° de l'option choisie: "
    echo -e "\n${BOLD}Sélectionner le fichier iso à graver sur USB :${ALL_OFF}"
    select CHOIX_ISO in "${liste_isos[@]}"; do
        if contains_element "$CHOIX_ISO" "${liste_isos[@]}"; then
            break
        else
            invalid_option
        fi
    done
    PATH_TO_ISO="${DIR_ISOS}/${CHOIX_ISO}"
fi

echo ""
msg "L'ISO suivante sera écrite sur la clé USB : ${PATH_TO_ISO}"

# date +%Y-%m-%d" "%H:%M:%S => 2012-12-13 19:46:11
DATEDUJOUR=$(date +%Y-%m-%d" "%H:%M:%S)

read_key "Brancher une clé USB"
sleep 1

# 1) Test si 1 clé USB a été branchée
is_usb_key_attached=$(journalctl --since="${DATEDUJOUR}" | grep -E "\[sd[b-z]\].*Attached SCSI removable disk" | awk '{print $8}' | sed -e "s/\[//" | sed -e "s/\]//")
if [[ $is_usb_key_attached == "" ]]; then
    die "Aucne clé USB n'a été branchée."
    IS_USB_KEY=0
else
    DEVICE_USB_KEY=${is_usb_key_attached}
    IS_USB_KEY=1
fi

# 2) Test si la clé USB est toujours branchée
if [[ $IS_USB_KEY -eq 1 ]]; then
    is_usb_key_disconnect=$(journalctl --since="${DATEDUJOUR}" | grep -E "USB disconnect, device number")
    echo ${is_usb_key_disconnect} | tr "[:upper:]" "[:lower:]" | grep -q disconnect
    if [[ $? -eq 0 ]]; then
        die "La clé USB a été débranchée."
        IS_USB_KEY=0
    else
        IS_USB_KEY=2
    fi
fi

# 3) Test si la clé USB n'est pas montée
if [[ $IS_USB_KEY -eq 2 ]]; then
    is_usb_key_mounted=$(lsblk | grep -E "$DEVICE_USB_KEY""[1-9]" | awk '{print $7}')
    echo ${is_usb_key_mounted} | tr "[:upper:]" "[:lower:]" | grep -q media
    if [[ $? -eq 0 ]]; then
        die "La clé USB est montée."
        IS_USB_KEY=0
    else
        IS_USB_KEY=3
    fi
fi

# 4) Test si taille clé USB > taille iso
if [[ $IS_USB_KEY -eq 3 ]]; then
#    size_usb_key=$(fdisk -l /dev/$DEVICE_USB_KEY 2> /dev/null | awk '{print $4}' | grep -E "octets" | sed -e "s/.octets,//")
    size_usb_key=$(fdisk -l /dev/$DEVICE_USB_KEY 2> /dev/null | awk '/octets,/ {print $5}' | sed -e "s/.octets,//")
    size_iso=$(ls -la $PATH_TO_ISO | awk '{print $5}')
    if [[ $size_iso -ge $size_usb_key ]] ; then
        die "Taille du fichier ISO >= Taille de la clé USB << ""$DEVICE_USB_KEY"" >> ."
    else
        IS_USB_KEY=4
    fi
fi

# 5) Commande dd bs=4M if=/path/to/archlinux.iso of=/dev/sdx
if [[ $IS_USB_KEY -eq 4 ]]; then
    # Calcul du sha1sum de ISO
    msg "Calcul du sha1sum de l'ISO ..."
    sha1sum_iso=$(sha1sum $PATH_TO_ISO | cut -d " " -f 1)
    # Écriture de l'ISO sur la clé USB
    msg "Écriture de l'ISO sur la clé USB << ""$DEVICE_USB_KEY"" >> ..."
    dd bs=4M if=$PATH_TO_ISO of=/dev/$DEVICE_USB_KEY 2>/dev/null
    if [[ $? -ne 0 ]]; then
        die "Écriture de l'ISO sur la clé USB << ""$DEVICE_USB_KEY"" >> impossible."
    fi
    sync
    # Calcul du sha1sum de la clé USB
    msg "Calcul du sha1sum de la clé USB << ""$DEVICE_USB_KEY"" >> ..."
    sha1sum_usb=$(dd if=/dev/$DEVICE_USB_KEY count=$(( $(stat -c %s $PATH_TO_ISO) / 512 )) 2>/dev/null | sha1sum | cut -d " " -f 1)
    # Test si sha1sum ok
    if [[ $sha1sum_usb != $sha1sum_iso ]] ;then
        die "Données sur la clé USB << ""$DEVICE_USB_KEY"" >> erronées."
    fi
fi

# FIN
msg "Écriture de l'ISO sur la clé USB << ""$DEVICE_USB_KEY"" >> réalisée avec succès."

read_key "Retirer la clé USB"

exit 0
