#!/usr/bin/env bash

#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2013, 2015, 2016
#
# Version : 04
#

# COULEURS
Bold=$(tput bold)
Underline=$(tput sgr 0 1)
Reset=$(tput sgr0)

# NOMS FICHIERS
NAME_DIR_REPOLOCAL=00-repolocal
NAME_REPOLOCAL=repolocal


# FONCTIONS
msg_titre() {
        local mesg=$1; shift
        printf "${Bold}${mesg}${Reset}\n" "$@" >&2
}


clear

msg_titre " +----------------------------------------+"
msg_titre " |                                        |"
msg_titre " |            M A J REPO-LOCAL            |"
msg_titre " |                                        |"
msg_titre " +----------------------------------------+"

#sleep 0.5

cd $HOME/${NAME_DIR_REPOLOCAL}/

rm -f ${NAME_REPOLOCAL}.db.tar.gz
rm -f ${NAME_REPOLOCAL}.files.tar.gz

#
# Si pas de -any.pkg.tar.gz
#repo-add ${NAME_REPOLOCAL}.db.tar.gz *-x86_64.pkg.tar.gz
#
# Si -any.pkg.tar.gz
#repo-add ${NAME_REPOLOCAL}.db.tar.gz *.pkg.tar.gz
#
# Si -any.pkg et tar.xz
repo-add ${NAME_REPOLOCAL}.db.tar.gz *.pkg.tar.*

# Supprimé suite maj pacman 5.0.0
# repo-add -f ${NAME_REPOLOCAL}.files.tar.gz *.pkg.tar.*

cd

exit 0
