#!/usr/bin/env bash
#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2015
# Version : 01

## POUR TEST
#set -x

# REPERTOIRES
DIR_SUDOERS=/etc

## POUR TEST
#DIR_SUDOERS=/home/jnd/01-scripts/Maj-sudoers
##
NAME_SUDOERS=sudoers
NAME_SUDOERS_PACNEW=sudoers.pacnew

# UTILISATEUR = jnd
USERNAME=jnd

# TIMESTAMP_TIMEOUT = 20 minutes
TIMESTAMP_TIMEOUT=20

# COLORS
# Regular Colors
Normal='\e[0m'          # Normal
Black='\e[0;30m'        # Black
Blue='\e[0;34m'         # Blue
Cyan='\e[0;36m'         # Cyan
Green='\e[0;32m'        # Green
Purple='\e[0;35m'       # Purple
Red='\e[0;31m'          # Red
White='\e[0;37m'        # White
Yellow='\e[0;33m'       # Yellow
# Bold
BBlack='\e[1;30m'       # Black
BBlue='\e[1;34m'        # Blue
BCyan='\e[1;36m'        # Cyan
BGreen='\e[1;32m'       # Green
BPurple='\e[1;35m'      # Purple
BRed='\e[1;31m'         # Red
BWhite='\e[1;37m'       # White
BYellow='\e[1;33m'      # Yellow

#
# FONCTIONS
#
msg() {
  local mesg=$1; shift
  printf "${BWhite}:: ${mesg}${Normal}\n" "$@" >&2
}

msg_titre() {
  local mesg=$1; shift
  printf "${BWhite}${mesg}${Normal}\n" "$@" >&2
}

error() {
  local mesg=$1; shift
  printf "${BRed}==> ERREUR:${BWhite} ${mesg}${Normal}\n" "$@" >&2
}

cleanup() {
  cd
  [[ $1 ]] && exit $1
}

die() {
  error "$*"
  cleanup 1
}

read_input_text(){
    read -p "$1 [O/N]: " OPTION
    echo ""
    OPTION=`echo "$OPTION" | tr '[:upper:]' '[:lower:]'`
}
#
# FIN FONCTIONS
#

#
# DEBUT DU SCRIPT
#

# => Passe en root
if [ ! $( id -u ) -eq 0 ]; then
    echo -e "\n${BYellow}Le script doit être exécuté en << root >>."
    echo -e "Entrer le mot de passe de << root >>${Normal}"
    exec su -c "${0} ${1}"
    exit ${?}
fi

# Titre
msg_titre "+--------------------------------------------------+"
msg_titre "|         Configuration du fichier sudoers         |"
msg_titre "+--------------------------------------------------+"


# Variable de retour : init à 9
retour=9

# La date du jour
LADATE=$(date +%Y-%m-%d)

# Répertoire de travail
DIR_WORK="${DIR_SUDOERS}"

## POUR TEST
# echo ""
# echo "POUR TEST : DIR_WORK = "${DIR_WORK}
##

cd "${DIR_WORK}"

# 1) MODIFS SUR FICHIERS TEMPS
cp ${NAME_SUDOERS_PACNEW} ${NAME_SUDOERS}.txt

# Uncomment to allow members of group wheel to execute any command
sed -i '/%wheel ALL=(ALL) ALL/s/^# //' ${NAME_SUDOERS}.txt
## Same thing without a password (not secure)
#sed -i '/%wheel ALL=(ALL) NOPASSWD: ALL/s/^# //' ${NAME_SUDOERS}.txt

# Modification de timestamp_timeout = 20 minutes
echo -e '\n## My Defaults timestamp_timeout = '${TIMESTAMP_TIMEOUT}' minutes' >> ${NAME_SUDOERS}.txt
echo -e 'Defaults:'"${USERNAME}"' timestamp_timeout='${TIMESTAMP_TIMEOUT}'' >> ${NAME_SUDOERS}.txt

echo ""
msg "Ces modifications seront apportées :"
sed '/#/d;/^$/d' ${NAME_SUDOERS}.txt

echo ""

# 2) FAIT MODIFS SI REPONSE = o ou O
read_input_text "Confirmer les modifications apportées"
    case "$OPTION" in
      "o")
          # Suppressions anciens fichiers backup
          echo ""
          msg "Suppression des anciens fichiers .backup existants."
          rm -v -f ${NAME_SUDOERS}.backup.*
          rm -v -f ${NAME_SUDOERS_PACNEW}.backup.*
          # Sauvegarde fichiers
          echo ""
          msg "Sauvegarde des fichiers existants."
          cp -v ${NAME_SUDOERS} ${NAME_SUDOERS}.backup.${LADATE}
          cp -v ${NAME_SUDOERS_PACNEW} ${NAME_SUDOERS_PACNEW}.backup.${LADATE}
          # Modification fichier sudoers
          echo ""
          msg "Modification de sudoers."
          mv -v ${NAME_SUDOERS}.txt ${NAME_SUDOERS}
          # Vérifications
          echo ""
          msg "Vérification de sudoers :"
          sed '/#/d;/^$/d' ${NAME_SUDOERS}
          # Supprime le fichier sudoers.pacnew
          echo ""
          msg "Suppression du fichier "${NAME_SUDOERS_PACNEW}"."
          rm -v -f "${NAME_SUDOERS_PACNEW}"
          # FIN OK
          cd
          echo ""
          msg "Modifications terminées."
          retour=0
          ;;
      *)
          # Réponse = N/n
          # 3) SUPPRIME FICHIERS TEMPS
          rm -f ${NAME_SUDOERS}.txt
          cd
          echo ""
          msg "Modifications non apportées."
          retour=1
          ;;
    esac

## POUR TEST
#set +x

cd
# ) FIN
exit $retour
