#!/usr/bin/env bash
#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2014-2012
#
# Version 0.4
#

## POUR TEST
#set -x

# VARIABLES
# NOM UTILSATEUR
NAME_USER=${USER}

IN_VIRTUAL_BOX=0
IS_REDIND_UPDATE_ACTIVE=1

NAME_REP_DEST_BOOT_MGR=""
NAME_DEST_BOOT_MGR=""

NAME_REP_INSTALLATION_PKG_REFIND="/usr/share/refind"
NAME_INSTALLATION_PKG_REFIND="refind_x64.efi"
NAME_CONF_INSTALLATION_PKG_REFIND="refind.conf-sample"
NAME_CONF_DEST_BOOT_MGR="refind.conf"
NAME_REP_ICONS_PKG_REFIND="icons"
NAME_REP_DEST_ICONS="icons"
NAME_REP_MY_ARCH_ICONS="/home/${NAME_USER}/01-scripts/Maj-refind/icones-arch"
#


# COULEURS
Bold=$(tput bold)
Underline=$(tput sgr 0 1)
Reset=$(tput sgr0)
# Regular Colors
Red=$(tput setaf 1)
Green=$(tput setaf 2)
Yellow=$(tput setaf 3)
Blue=$(tput setaf 4)
Purple=$(tput setaf 5)
Cyan=$(tput setaf 6)
White=$(tput setaf 7)
# Bold
BRed=${Bold}$(tput setaf 1)
BGreen=${Bold}$(tput setaf 2)
BYellow=${Bold}$(tput setaf 3)
BBlue=${Bold}$(tput setaf 4)
BPurple=${Bold}$(tput setaf 5)
BCyan=${Bold}$(tput setaf 6)
BWhite=${Bold}$(tput setaf 7)

#
# FONCTIONS
#
msg() {
  local mesg=$1; shift
  printf "${BWhite}:: ${mesg}${Reset}\n" "$@" >&2
}

msg_info() {
  local mesg=$1; shift
  printf "${BWhite}==> ${mesg}${Reset}\n" "$@" >&2
}

msg_titre() {
  local mesg=$1; shift
  printf "${BWhite}${mesg}${Reset}\n" "$@" >&2
}

msg_newline() {
    local mesg=$1; shift
    printf "\n" "$@" >&2
}

error() {
  local mesg=$1; shift
  printf "${BRed}==> ERREUR:${BWhite} ${mesg}${Reset}\n" "$@" >&2
}

cleanup() {
  cd
  [[ $1 ]] && exit $1
}

die() {
  error "$*"
  cleanup 1
}

# DANS VIRTUALBOX OU NON
# OUI ==> IN_VIRTUAL_BOX=1
# NON ==> IN_VIRTUAL_BOX=0
check_is_in_virtualbox() { #{{{
    local vbox=$(journalctl -b | grep -E "DMI:")
    echo ${vbox} | tr "[:upper:]" "[:lower:]" | grep -q virtualbox
    if (( $? == 0 )); then
        IN_VIRTUAL_BOX=1
    else
        IN_VIRTUAL_BOX=0
    fi
} #}}}

check_and_return_name_partition_esp() {
    local esp=$(LC_ALL=C fdisk -l | awk '/EFI System/ {print $1}')
    if [[ "${esp}" != "" ]];then
        IS_NAME_ESP_EXISTE=1
        NAME_PARTITION_ESP=${esp}
#        echo "une partition ESP existe et est : "${NAME_PARTITION_ESP}
    else
        IS_NAME_ESP_EXISTE=0
#        echo "PAS de partition ESP !"
    fi
}

check_if_refind_update_active() {
    local status=$(LC_ALL=C systemctl status refind_update.path 2> /dev/null | awk '/Active/ {print $2}')
    if [[ "${status}" == "active" ]];then
        IS_REDIND_UPDATE_ACTIVE=1
    else
        IS_REDIND_UPDATE_ACTIVE=0
    fi
}

#
# FIN FONCTIONS
#

#
# DEBUT DU SCRIPT
#

# nom du script = $0
# nombre d'argument = $#
# liste des arguments = $*
# => Passe en root
if (( EUID != 0 )); then
    printf '\n%s\n' "${BYellow}Le script $0 doit être exécuté en «root»."
    printf '%s\n' "Entrer le mot de passe de «root»${Reset}"
    exec su -c "${0} ${1}"
    exit ${?}
fi


# Titre
msg_titre "+----------------------------------------------+"
msg_titre "|    Suite à la mise à jour de refind          |"
msg_titre "|    Copie du fichier refind_x64.efi           |"
msg_titre "|    Copie du Répertoire icons                 |"
msg_titre "+----------------------------------------------+"

msg_newline

# POUR TEST =1 SINON =0
MISE_AU_POINT=0

# Test si dans VirtualBox
check_is_in_virtualbox
if (( $IN_VIRTUAL_BOX == 1 )); then
    msg_info "Installation dans Oracle VM VirtualBox."
    NAME_REP_DEST_BOOT_MGR="/boot/efi/EFI/BOOT"
    NAME_DEST_BOOT_MGR="bootx64.efi"
else
    msg_info "Installation réelle."
    NAME_REP_DEST_BOOT_MGR="/boot/efi/EFI/refind"
    NAME_DEST_BOOT_MGR="refind_x64.efi"
fi
msg_newline

check_if_refind_update_active
if (( $IS_REDIND_UPDATE_ACTIVE == 1 )); then
    msg_info "Service refind_update.path actif. Arrêt du service refind_update.path."
    systemctl stop refind_update.path
    systemctl disable refind_update.path
else
    msg_info "Service refind_update.path NON actif."
fi
msg_newline
msg_newline


# NAME_INSTALLATION_PKG_REFIND="refind_x64.efi"
msg "Copie de ${NAME_INSTALLATION_PKG_REFIND} dans ${NAME_REP_DEST_BOOT_MGR}/${NAME_DEST_BOOT_MGR}."
if (( $MISE_AU_POINT == 0 )); then
    cp -v ${NAME_REP_INSTALLATION_PKG_REFIND}/${NAME_INSTALLATION_PKG_REFIND} ${NAME_REP_DEST_BOOT_MGR}/${NAME_DEST_BOOT_MGR}
    msg_newline
else
    echo -e "\nMISE AU POINT - La commande suivante sera éxécutée :"
    echo -e "cp -v ${NAME_REP_INSTALLATION_PKG_REFIND}/${NAME_INSTALLATION_PKG_REFIND} ${NAME_REP_DEST_BOOT_MGR}/${NAME_DEST_BOOT_MGR}"
    msg_newline
fi

msg "Copie de ${NAME_REP_ICONS_PKG_REFIND} dans ${NAME_REP_DEST_BOOT_MGR}/."
if (( $MISE_AU_POINT == 0 )); then
    cp -R ${NAME_REP_INSTALLATION_PKG_REFIND}/${NAME_REP_ICONS_PKG_REFIND} ${NAME_REP_DEST_BOOT_MGR}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_1.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_1_ck.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_1_lts.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_1_zen.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_2.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_2_ck.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_2_lts.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_2_zen.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_3.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_3_ck.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_3_lts.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_3_zen.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_4.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_4_ck.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_4_lts.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_4_zen.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_5.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_5_ck.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_5_lts.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    cp -v ${NAME_REP_MY_ARCH_ICONS}/os_arch_5_zen.png ${NAME_REP_DEST_BOOT_MGR}/${NAME_REP_DEST_ICONS}/
    msg_newline
else
    echo -e "\nMISE AU POINT - La commande suivante sera éxécutée :"
    echo -e "cp -R ${NAME_REP_INSTALLATION_PKG_REFIND}/${NAME_REP_ICONS_PKG_REFIND} ${NAME_REP_DEST_BOOT_MGR}/"
    msg_newline
fi


# FIN
if (( $MISE_AU_POINT == 0 )); then
    msg "Fin de l'installation suite à la mise à jour de refind"
    msg_newline
# Vérifications
    msg_info "Pour vérifier le fichier ${NAME_REP_DEST_BOOT_MGR}/${NAME_CONF_DEST_BOOT_MGR}."
    msg_info "Entrer les commandes suivantes en USER :"
    msg_info "kwrite ${NAME_REP_DEST_BOOT_MGR}/${NAME_CONF_DEST_BOOT_MGR} &"
    msg_info "kwrite /usr/share/refind/refind.conf-sample &"
else
    echo -e "\nMISE AU POINT - Fin du test de l'installation suite à la mise à jour de refind"
    msg_newline
# Vérifications
    msg_info "Pour vérifier le fichier ${NAME_REP_DEST_BOOT_MGR}/${NAME_CONF_DEST_BOOT_MGR}."
    msg_info "Entrer la commande suivante en USER :"
    msg_info "kwrite ${NAME_REP_DEST_BOOT_MGR}/${NAME_CONF_DEST_BOOT_MGR} &"
    msg_info "kwrite /usr/share/refind/refind.conf-sample &"
fi


## POUR TEST
#set +x

cd
exit 0

#==============================================================================
# ESSAIS
#==============================================================================
