#!/usr/bin/env bash

#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2013, 2014, 2015
#
# Version 06
#

#
# COULEURS
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
BLUE="${BOLD}\e[1;34m"
GREEN="${BOLD}\e[1;32m"
RED="${BOLD}\e[1;31m"
YELLOW="${BOLD}\e[1;33m"

#
# FONCTIONS
read_input_text(){ #{{{
    read -p "$1 [O/N]: " OPTION
    echo ""
    OPTION=`echo "$OPTION" | tr '[:upper:]' '[:lower:]'`
} #}}}
#

# => Passe en root
if [ ! $( id -u ) -eq 0 ]; then
    echo -e "\n${YELLOW}Le script "$0" doit être exécuté en << root >>."
    echo -e "Entrer le mot de passe de << root >>${ALL_OFF}"
    exec su -c "${0} ${CMDLN_ARGS}"
    exit ${?}
fi

# Titre
echo "+-------------------------------------------------------------+"
echo "| Modification des options de compilation de Qt4              |"
echo "| Modification de /usr/share/qt4/mkspecs/common/g++-base.conf |"
echo "| Modification de /usr/share/qt4/mkspecs/common/gcc-base.conf |"
echo "+-------------------------------------------------------------+"
echo ""

# La date du jour
#LADATE=`date +%Y-%m-%d_%H-%M`;
LADATE=`date +%Y-%m-%d`;

# Le répertoire
cd /usr/share/qt4/mkspecs/common

# 1) MODIFS SUR FICHIERS TEMPS
cp g++-base.conf g++-base.conf.txt
cp gcc-base.conf gcc-base.conf.txt
if [ -f "/etc/makepkg.conf" ]; then
  # Get CXXFLAGS from makepkg.conf
  eval $(grep '^CXXFLAGS=' "/etc/makepkg.conf")
  if [ -n "${CXXFLAGS}" ]; then
    # Changes the current line with my CXXFLAGS
    sed -i "/^QMAKE_CFLAGS_RELEASE/c\QMAKE_CFLAGS_RELEASE        += ${CXXFLAGS}" gcc-base.conf.txt
    sed -i "/^QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO/c\QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += ${CXXFLAGS} -g" g++-base.conf.txt
  fi
fi
echo ":: Ces modifications seront apportées :"
echo "=> gcc-base.conf :"
cat gcc-base.conf.txt | grep -E "^QMAKE_CFLAGS_RELEASE"
echo ""
echo "=> g++-base.conf :"
cat g++-base.conf.txt | grep -E "^QMAKE_CFLAGS_RELEASE"
echo ""

# 2) FAIT MODIFS SI REPONSE = o ou O
read_input_text "Confirmer les modifications apportées"
  case "$OPTION" in
    "o")
        echo ":: Suppression des anciens g++-base.conf.backup-AAAA-MM-JJ"
        echo "::          et des anciens gcc-base.conf.backup-AAAA-MM-JJ"
        echo ""
        rm -f g++-base.conf.backup-*
        rm -f gcc-base.conf.backup-*

        echo ":: Sauvegarde de g++-base.conf original en g++-base.conf.backup-${LADATE}"
        echo "::         et de gcc-base.conf original en gcc-base.conf.backup-${LADATE}"
        echo ""
        cp g++-base.conf g++-base.conf.backup-${LADATE}
        cp gcc-base.conf gcc-base.conf.backup-${LADATE}

        echo ":: Modification de g++-base.conf et de gcc-base.conf"
        echo ""
        mv gcc-base.conf.txt gcc-base.conf
        mv g++-base.conf.txt g++-base.conf

        echo ":: Vérification :"
        echo "=> gcc-base.conf :"
        cat gcc-base.conf | grep -E "^QMAKE_CFLAGS_RELEASE"
        echo ""
        echo "=> g++-base.conf :"
        cat g++-base.conf | grep -E "^QMAKE_CFLAGS_RELEASE"
        echo ""

        cd
        echo ":: Modifications terminées."
        echo ""
        ret=0
        ;;
    *)
        # 3) SUPPRIME FICHIERS TEMPS
        rm -f g++-base.conf.txt
        rm -f gcc-base.conf.txt
        cd
        echo ":: Modifications non apportées."
        echo ""
        ret=1
        ;;
  esac
  

# ) FIN
exit $ret
