#!/usr/bin/bash
#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2014
# Version : 01

## POUR TEST
#set -x

# REPERTOIRES
## TEST
#NAME_DIR_EFI="/home/jnd/01-scripts/Maj-refind-conf/"
##
NAME_DIR_EFI="/boot/efi/EFI/refind"
NAME_REFIND_CONF="refind.conf"

USERNAME="jnd"


# COLORS
# Regular Colors
Normal='\e[0m'          # Normal
Black='\e[0;30m'        # Black
Blue='\e[0;34m'         # Blue
Cyan='\e[0;36m'         # Cyan
Green='\e[0;32m'        # Green
Purple='\e[0;35m'       # Purple
Red='\e[0;31m'          # Red
White='\e[0;37m'        # White
Yellow='\e[0;33m'       # Yellow
# Bold
BBlack='\e[1;30m'       # Black
BBlue='\e[1;34m'        # Blue
BCyan='\e[1;36m'        # Cyan
BGreen='\e[1;32m'       # Green
BPurple='\e[1;35m'      # Purple
BRed='\e[1;31m'         # Red
BWhite='\e[1;37m'       # White
BYellow='\e[1;33m'      # Yellow

#
# FONCTIONS
#
msg() {
  local mesg=$1; shift
  printf "${BWhite}:: ${mesg}${Normal}\n" "$@" >&2
}

msg_titre() {
  local mesg=$1; shift
  printf "${BWhite}${mesg}${Normal}\n" "$@" >&2
}


#
# DEBUT DU SCRIPT
#

cd
msg "Ouverture du fichier /usr/share/refind/refind.conf-sample avec kwrite"
msg "Pour comparaison avec refind.conf modifié."
kwrite /usr/share/refind/refind.conf-sample &

# => Passe en root
if [ ! $( id -u ) -eq 0 ]; then
    echo -e "\n${BYellow}Le script doit être exécuté en << root >>."
    echo -e "Entrer le mot de passe de << root >>${Normal}"
    exec su -c "${0} ${1}"
    exit ${?}
fi

# Titre
msg_titre "+----------------------------------------------------+"
msg_titre "| Modification du fichier de configuration de rEFInd |"
msg_titre "| Version de rEFInd = 0.8.3                          |"
msg_titre "| Modification de /boot/efi/EFI/refind/refind.conf   |"
msg_titre "+----------------------------------------------------+"

# La date du jour
LADATE=`date +%Y-%m-%d`;

# Suppressions ancien fichier
echo ""
msg "Suppression des anciens fichiers .backup existants."
rm -v -f ${NAME_DIR_EFI}/${NAME_REFIND_CONF}.backup.*

# Sauvegarde fichier existant
echo ""
msg "Sauvegarde des fichiers existants."
cp -v ${NAME_DIR_EFI}/${NAME_REFIND_CONF} ${NAME_DIR_EFI}/${NAME_REFIND_CONF}.backup.${LADATE}

# Copie nouveau fichier
echo ""
msg "Copie du nouveau fichier de configuration de rEFInd."
cp -v /usr/share/refind/refind.conf-sample ${NAME_DIR_EFI}/${NAME_REFIND_CONF}

# rEFInd 0.8.3 :
# A ETUDIER
# #scanfor internal,external,optical,manual => scanfor internal,hdbios,external,optical,manual
# #uefi_deep_legacy_scan => uefi_deep_legacy_scan true
# A MODIFIER
# #scan_all_linux_kernels false => scan_all_linux_kernels false
#
# Modification du nouveau fichier
echo ""
msg "Modification du nouveau fichier de configuration de rEFInd."
sed -i "/^timeout/c\timeout 2" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#resolution 1024 768/c\resolution 1024 768" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#showtools/c\showtools shell,about,shutdown,reboot,firmware" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
# A ETUDIER
# OK INSTALLATION REELLE
# PAS OK : RAJOUTES ENTRÉES DS NVRAM => PLUS DE BOOT !!!
#sed -i "/^#scanfor/c\scanfor internal,hdbios,external,optical,manual" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
# NE SEMBLE PAS OBLIGATOIRE ( PAR DEFAUT )
#sed -i "/^#uefi_deep_legacy_scan/c\uefi_deep_legacy_scan true" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
#
sed -i "/^#dont_scan_files/c\dont_scan_files BOOTX64.EFI,fallback.efi,shim.efi,shim-fedora.efi,gcdx64.efi,MokManager.efi" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#scan_all_linux_kernels/c\scan_all_linux_kernels false" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}

# A REVOIR
# Visualisation du nouveau fichier
echo ""
msg "Visualisation du nouveau fichier "${NAME_REFIND_CONF}"."
msg "A comparer avec /usr/share/refind/refind.conf-sample ouvert dans kwrite"
#sed '/#/d;/^$/d' ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed '/#/d;/^$/d;/^menuentry/d;/^}/d;/^\t/d' ${NAME_DIR_EFI}/${NAME_REFIND_CONF}

# Sauvegarde du nouveau fichier ds ~/09-Fichiers-Conf/Refind-Fichiers-Conf/
echo ""
msg "Sauvegarde des nouveaux fichiers dans ~/09-Fichiers-Conf/Refind-Fichiers-Conf/."
cp -v ${NAME_DIR_EFI}/${NAME_REFIND_CONF} /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}
cp -v ${NAME_DIR_EFI}/${NAME_REFIND_CONF}.backup.${LADATE} /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}.backup.${LADATE}
chown ${USERNAME}:users /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}
chown ${USERNAME}:users /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}.backup.${LADATE}

## POUR TEST
#set +x

exit 0

