#!/usr/bin/env bash
#
# Author: Jean-Noel Dot  <prenom nom @ fournisseur.fr> 2014-2017
# Version : 03

## POUR TEST
#set -x

# REPERTOIRES
## TEST
#NAME_DIR_EFI="/home/jnd/01-scripts/Maj-refind-conf/"
##
NAME_DIR_EFI="/boot/efi/EFI/refind"
NAME_REFIND_CONF="refind.conf"

USERNAME=${USER}


# COULEURS
Bold=$(tput bold)
Underline=$(tput sgr 0 1)
Reset=$(tput sgr0)
# Regular Colors
Red=$(tput setaf 1)
Green=$(tput setaf 2)
Yellow=$(tput setaf 3)
Blue=$(tput setaf 4)
Purple=$(tput setaf 5)
Cyan=$(tput setaf 6)
White=$(tput setaf 7)
# Bold
BRed=${Bold}$(tput setaf 1)
BGreen=${Bold}$(tput setaf 2)
BYellow=${Bold}$(tput setaf 3)
BBlue=${Bold}$(tput setaf 4)
BPurple=${Bold}$(tput setaf 5)
BCyan=${Bold}$(tput setaf 6)
BWhite=${Bold}$(tput setaf 7)

#
# FONCTIONS
#
msg() {
  local mesg=$1; shift
  printf "${BWhite}:: ${mesg}${Reset}\n" "$@" >&2
}

msg_titre() {
  local mesg=$1; shift
  printf "${BWhite}${mesg}${Reset}\n" "$@" >&2
}

msg_newline() {
    local mesg=$1; shift
    printf "\n" "$@" >&2
}


#
# DEBUT DU SCRIPT
#

# Version de rEFInd
VERSION_REFIND_EFI=$(pacman -Qi "refind-efi" 2>/dev/null | awk '/Version/ {print $3}' | sed -e "s/-[0-9]$//")

cd
msg "Ouverture du fichier /usr/share/refind/refind.conf-sample avec kwrite"
msg "Pour comparaison avec refind.conf modifié."
kwrite /usr/share/refind/refind.conf-sample &

# => Passe en root
if (( EUID != 0 )); then
    printf '\n%s\n' "${BYellow}Le script $0 doit être exécuté en «root»."
    printf '%s\n' "Entrer le mot de passe de «root»${Reset}"
    exec su -c "${0} ${1}"
    exit ${?}
fi

# Titre
msg_titre "+----------------------------------------------------+"
msg_titre "| Modification du fichier de configuration de rEFInd |"
# msg_titre "| Version de rEFInd = 0.8.5                          |"
msg_titre "| Version de rEFInd = ${VERSION_REFIND_EFI}                          |"
msg_titre "| Modification de /boot/efi/EFI/refind/refind.conf   |"
msg_titre "+----------------------------------------------------+"

# La date du jour
LADATE=`date +%Y-%m-%d`;

# Suppressions ancien fichier
msg_newline
msg "Suppression des anciens fichiers .backup existants."
rm -v -f ${NAME_DIR_EFI}/${NAME_REFIND_CONF}.backup.*

# Sauvegarde fichier existant
msg_newline
msg "Sauvegarde des fichiers existants."
cp -v ${NAME_DIR_EFI}/${NAME_REFIND_CONF} ${NAME_DIR_EFI}/${NAME_REFIND_CONF}.backup.${LADATE}

# Copie nouveau fichier
msg_newline
msg "Copie du nouveau fichier de configuration de rEFInd."
cp -v /usr/share/refind/refind.conf-sample ${NAME_DIR_EFI}/${NAME_REFIND_CONF}

# rEFInd 0.8.3 :
# A ETUDIER
# #scanfor internal,external,optical,manual => scanfor internal,hdbios,external,optical,manual
# #uefi_deep_legacy_scan => uefi_deep_legacy_scan true
# A MODIFIER
# #scan_all_linux_kernels false => scan_all_linux_kernels false
#
# Modification du nouveau fichier
msg_newline
msg "Modification du nouveau fichier de configuration de rEFInd."
sed -i "/^timeout/c\timeout 2" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#resolution 1024 768/c\resolution 1024 768" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#showtools/c\showtools shell,about,shutdown,reboot,firmware" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
# A ETUDIER
# OK INSTALLATION REELLE
# PAS OK : RAJOUTES ENTRÉES DS NVRAM => PLUS DE BOOT !!!
#sed -i "/^#scanfor/c\scanfor internal,hdbios,external,optical,manual" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
# NE SEMBLE PAS OBLIGATOIRE ( PAR DEFAUT )
#sed -i "/^#uefi_deep_legacy_scan/c\uefi_deep_legacy_scan true" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
#
sed -i "/^#dont_scan_files/c\dont_scan_files BOOTX64.EFI,fallback.efi,shim.efi,shim-fedora.efi,gcdx64.efi,MokManager.efi" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#scan_all_linux_kernels/c\scan_all_linux_kernels false" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed -i "/^#fold_linux_kernels/c\fold_linux_kernels false" ${NAME_DIR_EFI}/${NAME_REFIND_CONF}

# A REVOIR
# Visualisation du nouveau fichier
msg_newline
msg "Visualisation du nouveau fichier "${NAME_REFIND_CONF}"."
msg "A comparer avec /usr/share/refind/refind.conf-sample ouvert dans kwrite"
#sed '/#/d;/^$/d' ${NAME_DIR_EFI}/${NAME_REFIND_CONF}
sed '/#/d;/^$/d;/^menuentry/d;/^}/d;/^\t/d' ${NAME_DIR_EFI}/${NAME_REFIND_CONF}

# Sauvegarde du nouveau fichier ds ~/09-Fichiers-Conf/Refind-Fichiers-Conf/
msg_newline
msg "Sauvegarde des nouveaux fichiers dans ~/09-Fichiers-Conf/Refind-Fichiers-Conf/."
cp -v ${NAME_DIR_EFI}/${NAME_REFIND_CONF} /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}
cp -v ${NAME_DIR_EFI}/${NAME_REFIND_CONF}.backup.${LADATE} /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}.backup.${LADATE}
chown ${USERNAME}:users /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}
chown ${USERNAME}:users /home/${USERNAME}/09-Fichiers-Conf/Refind-Fichiers-Conf/${NAME_REFIND_CONF}.backup.${LADATE}

## POUR TEST
#set +x

exit 0

